# Modeling

In [1]:
from function import *

In [2]:
# load data
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [3]:
train.tail()

USER_ID_hash                    COUPON_ID_hash  \
2517201  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517202  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517203  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517204  295ce0aacf52e06ecde42ae6b386aef4  7f7f124e5b2a82e1dd3453d21b3eba49   
2517205  e497d37b6d8b78d3382177f43a9d22a6  e94cbaf8b9848ad2c6b5bc243965f7c8   

        CAPSULE_TEXT  GENRE_NAME SEX_ID  USABLE_DATE_MON  USABLE_DATE_TUE  \
2517201          Spa         Spa      f              1.0              1.0   
2517202          Spa         Spa      f              1.0              1.0   
2517203          Spa         Spa      f              1.0              1.0   
2517204          Spa         Spa      f              1.0              1.0   
2517205   Hair salon  Hair salon      f              0.0              1.0   

         USABLE_DATE_WED  USABLE_DATE_THU  USABLE_DATE_FRI      ...       \
2517201              1.0              1.0              1.0      ...        
2517202              1.0              1.0              1.0      ...        
2517203              1.0              1.0              1.0      ...        
2517204              1.0              1.0              0.0      ...        
2517205              1.0              1.0              1.0      ...        

         REG_month  REG_weekday  REG_hour  PRICE_RATE CATALOG_PRICE  \
2517201          9            0         0          73         36800   
2517202          9            0         0          73         36800   
2517203          9            0         0          73         36800   
2517204         11            3        21          57         10500   
2517205         10            4        23          61         15330   

        DISCOUNT_PRICE DISPPERIOD  VALIDPERIOD  AGE  PURCHASE_FLG  
2517201           9800          3        178.0   39             0  
2517202           9800          3        178.0   39             0  
2517203           9800          3        178.0   39             0  
2517204           4500          2        179.0   25             1  
2517205           5970          2         67.0   53             1  

[5 rows x 36 columns]

In [4]:
# Make Lebel Encoder
ls = ['CAPSULE_TEXT', 'GENRE_NAME', 'SEX_ID', 'large_area_name', 'ken_name', 'small_area_name']

for i in range(len(ls)):
    le = LabelEncoder()
    le.fit(train[ls[i]])
    col = le.transform(train[ls[i]])
    train[ls[i]] = col

In [5]:
# Make Lebel Encoder
ls = ['CAPSULE_TEXT', 'GENRE_NAME', 'SEX_ID', 'large_area_name', 'ken_name', 'small_area_name']

for i in range(len(ls)):
    le = LabelEncoder()
    le.fit(test[ls[i]])
    col = le.transform(test[ls[i]])
    test[ls[i]] = col

In [6]:
train.tail()

USER_ID_hash                    COUPON_ID_hash  \
2517201  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517202  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517203  5fc8a0b419f579e539d28c63f3d44b7b  5febdd370f0f8e64b9be29b418ab06c5   
2517204  295ce0aacf52e06ecde42ae6b386aef4  7f7f124e5b2a82e1dd3453d21b3eba49   
2517205  e497d37b6d8b78d3382177f43a9d22a6  e94cbaf8b9848ad2c6b5bc243965f7c8   

         CAPSULE_TEXT  GENRE_NAME  SEX_ID  USABLE_DATE_MON  USABLE_DATE_TUE  \
2517201            21          12       0              1.0              1.0   
2517202            21          12       0              1.0              1.0   
2517203            21          12       0              1.0              1.0   
2517204            21          12       0              1.0              1.0   
2517205             8           4       0              0.0              1.0   

         USABLE_DATE_WED  USABLE_DATE_THU  USABLE_DATE_FRI      ...       \
2517201              1.0              1.0              1.0      ...        
2517202              1.0              1.0              1.0      ...        
2517203              1.0              1.0              1.0      ...        
2517204              1.0              1.0              0.0      ...        
2517205              1.0              1.0              1.0      ...        

         REG_month  REG_weekday  REG_hour  PRICE_RATE  CATALOG_PRICE  \
2517201          9            0         0          73          36800   
2517202          9            0         0          73          36800   
2517203          9            0         0          73          36800   
2517204         11            3        21          57          10500   
2517205         10            4        23          61          15330   

         DISCOUNT_PRICE  DISPPERIOD  VALIDPERIOD  AGE  PURCHASE_FLG  
2517201            9800           3        178.0   39             0  
2517202            9800           3        178.0   39             0  
2517203            9800           3        178.0   39             0  
2517204            4500           2        179.0   25             1  
2517205            5970           2         67.0   53             1  

[5 rows x 36 columns]

In [7]:
test.tail()

USER_ID_hash                    COUPON_ID_hash  \
7090625  2f0a2f36a9f63b6ba2fa3a7e53bef906  f9c657ce7ca80b3766ced3a9a3c709bb   
7090626  6ae7811a9c7c58546d6a1567ab098c21  f9c657ce7ca80b3766ced3a9a3c709bb   
7090627  a417308c6a79ae0d86976401ec2e3b04  f9c657ce7ca80b3766ced3a9a3c709bb   
7090628  4937ec1c86e71d901c4ccc0357cff0b1  f9c657ce7ca80b3766ced3a9a3c709bb   
7090629  280f0cedda5c4b171ee6245889659571  f9c657ce7ca80b3766ced3a9a3c709bb   

         CAPSULE_TEXT  GENRE_NAME  SEX_ID  USABLE_DATE_MON  USABLE_DATE_TUE  \
7090625             7           5       0              1.0              1.0   
7090626             7           5       1              1.0              1.0   
7090627             7           5       0              1.0              1.0   
7090628             7           5       0              1.0              1.0   
7090629             7           5       0              1.0              1.0   

         USABLE_DATE_WED  USABLE_DATE_THU  USABLE_DATE_FRI ...   REG_year  \
7090625              1.0              1.0              1.0 ...       2011   
7090626              1.0              1.0              1.0 ...       2011   
7090627              1.0              1.0              1.0 ...       2012   
7090628              1.0              1.0              1.0 ...       2011   
7090629              1.0              1.0              1.0 ...       2011   

         REG_month  REG_weekday  REG_hour  PRICE_RATE  CATALOG_PRICE  \
7090625         12            0        15          50          28000   
7090626          8            2         0          50          28000   
7090627          4            3        12          50          28000   
7090628          2            6        10          50          28000   
7090629          2            3        15          50          28000   

         DISCOUNT_PRICE  DISPPERIOD  VALIDPERIOD  AGE  
7090625           14000           4         67.0   24  
7090626           14000           4         67.0   41  
7090627           14000           4         67.0   35  
7090628           14000           4         67.0   59  
7090629           14000           4         67.0   38  

[5 rows x 35 columns]

In [8]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
train_vif = train.drop(['USER_ID_hash', 'COUPON_ID_hash', 'PURCHASE_FLG'], axis = 1)
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(train_vif.values, i) for i in range(train_vif.shape[1])]
vif["features"] = train_vif.columns
vif

VIF Factor                    features
0   7.603343e+01                CAPSULE_TEXT
1   5.991143e+01                  GENRE_NAME
2   1.920396e+00                      SEX_ID
3   3.806329e+01             USABLE_DATE_MON
4   5.347335e+01             USABLE_DATE_TUE
5   1.057954e+02             USABLE_DATE_WED
6   1.367520e+02             USABLE_DATE_THU
7   4.510812e+01             USABLE_DATE_FRI
8   2.508113e+01             USABLE_DATE_SAT
9   2.329885e+01             USABLE_DATE_SUN
10  3.049509e+01         USABLE_DATE_HOLIDAY
11  3.152730e+01  USABLE_DATE_BEFORE_HOLIDAY
12  1.038989e+01             large_area_name
13  7.092425e+00                    ken_name
14  3.944137e+00             small_area_name
15  6.959768e+09               DISPFROM_year
16  6.396254e+02              DISPFROM_month
17  3.355234e+00            DISPFROM_weekday
18  2.528136e+03               DISPFROM_hour
19  6.969898e+09                DISPEND_year
20  6.472590e+02               DISPEND_month
21  3.766961e+00             DISPEND_weekday
22  6.899069e+03                DISPEND_hour
23  2.473608e+07                    REG_year
24  8.855452e+00                   REG_month
25  3.263598e+00                 REG_weekday
26  6.536256e+00                    REG_hour
27  4.303744e+01                  PRICE_RATE
28  1.043242e+01               CATALOG_PRICE
29  1.111342e+01              DISCOUNT_PRICE
30  4.784566e+00                  DISPPERIOD
31  1.268797e+01                 VALIDPERIOD
32  1.981162e+01                         AGE

In [9]:
train = train.drop(['GENRE_NAME', 'USABLE_DATE_WED', 'USABLE_DATE_THU', 'DISPFROM_year', 'DISPFROM_month', 
                    'DISPFROM_hour', 'DISPEND_year', 'DISPEND_month', 'DISPEND_hour', 'REG_year',
                    'USABLE_DATE_BEFORE_HOLIDAY', 'PRICE_RATE'], axis = 1)

In [12]:
train_vif = train.drop(['USER_ID_hash', 'COUPON_ID_hash', 'PURCHASE_FLG'], axis = 1)
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(train_vif.values, i) for i in range(train_vif.shape[1])]
vif["features"] = train_vif.columns
vif

VIF Factor             features
0     3.819068         CAPSULE_TEXT
1     1.914609               SEX_ID
2    32.507212      USABLE_DATE_MON
3    40.831300      USABLE_DATE_TUE
4    35.841005      USABLE_DATE_FRI
5    14.560595      USABLE_DATE_SAT
6    21.975471      USABLE_DATE_SUN
7    29.434753  USABLE_DATE_HOLIDAY
8     9.817095      large_area_name
9     6.887622             ken_name
10    3.912615      small_area_name
11    3.252104     DISPFROM_weekday
12    3.632632      DISPEND_weekday
13    4.376318            REG_month
14    3.213905          REG_weekday
15    6.319085             REG_hour
16    6.949707        CATALOG_PRICE
17    7.306464       DISCOUNT_PRICE
18    2.799607           DISPPERIOD
19   10.884635          VALIDPERIOD
20   17.684595                  AGE

### 1. Select columns & Encoding

In [15]:
train.columns

Index(['USER_ID_hash', 'COUPON_ID_hash', 'CAPSULE_TEXT', 'SEX_ID',
       'USABLE_DATE_MON', 'USABLE_DATE_TUE', 'USABLE_DATE_FRI',
       'USABLE_DATE_SAT', 'USABLE_DATE_SUN', 'USABLE_DATE_HOLIDAY',
       'USABLE_DATE_BEFORE_HOLIDAY', 'large_area_name', 'ken_name',
       'small_area_name', 'DISPFROM_weekday', 'DISPEND_weekday', 'REG_month',
       'REG_weekday', 'REG_hour', 'PRICE_RATE', 'CATALOG_PRICE',
       'DISCOUNT_PRICE', 'DISPPERIOD', 'VALIDPERIOD', 'AGE', 'PURCHASE_FLG'],
      dtype='object')

In [4]:
test.columns

Index(['USER_ID_hash', 'COUPON_ID_hash', 'CAPSULE_TEXT', 'GENRE_NAME',
       'SEX_ID', 'USABLE_DATE_MON', 'USABLE_DATE_TUE', 'USABLE_DATE_WED',
       'USABLE_DATE_THU', 'USABLE_DATE_FRI', 'USABLE_DATE_SAT',
       'USABLE_DATE_SUN', 'USABLE_DATE_HOLIDAY', 'USABLE_DATE_BEFORE_HOLIDAY',
       'large_area_name', 'ken_name', 'small_area_name', 'DISPFROM_year',
       'DISPFROM_month', 'DISPFROM_weekday', 'DISPFROM_hour', 'DISPEND_year',
       'DISPEND_month', 'DISPEND_weekday', 'DISPEND_hour', 'REG_year',
       'REG_month', 'REG_weekday', 'REG_hour', 'PRICE_RATE', 'CATALOG_PRICE',
       'DISCOUNT_PRICE', 'DISPPERIOD', 'VALIDPERIOD', 'AGE'],
      dtype='object')

In [13]:
# Select columns
category = ['CAPSULE_TEXT', 'SEX_ID', 'USABLE_DATE_MON', 'USABLE_DATE_TUE', 'USABLE_DATE_FRI',
            'USABLE_DATE_SAT', 'USABLE_DATE_SUN', 'USABLE_DATE_HOLIDAY', 'large_area_name', 
            'ken_name', 'small_area_name', 'DISPFROM_weekday', 'DISPEND_weekday', 'REG_month', 
            'REG_weekday', 'REG_hour']
continuous = ['CATALOG_PRICE', 'DISCOUNT_PRICE', 'DISPPERIOD', 'VALIDPERIOD', 'AGE']

In [14]:
# make train/test data

train_cols, test_cols = [], []

# category
for cat in category:
    train_tok, test_tok = category_to_ohe(train[cat],test[cat])
    train_cols.append(train_tok)
    test_cols.append(test_tok)    

# continuous
for con in continuous:
    train_cols.append(train[con].values.reshape(len(train),1))
    test_cols.append(test[con].values.reshape(len(test),1))
 

In [15]:
# stack train/test data
X_train = np.hstack(tuple(each for each in train_cols))
X_test = np.hstack(tuple(each for each in test_cols))
y_train = train['PURCHASE_FLG']

In [16]:
X_train

array([[  3.,   0.,   1., ...,   4., 126.,  25.],
       [  3.,   0.,   1., ...,   4., 126.,  25.],
       [  3.,   0.,   1., ...,   4., 126.,  25.],
       ...,
       [ 21.,   0.,   1., ...,   3., 178.,  39.],
       [ 21.,   0.,   1., ...,   2., 179.,  25.],
       [  8.,   0.,   0., ...,   2.,  67.,  53.]])

In [17]:
X_test

array([[  3.,   0.,   1., ...,   4., 118.,  25.],
       [  3.,   0.,   1., ...,   4., 118.,  34.],
       [  3.,   1.,   1., ...,   4., 118.,  41.],
       ...,
       [  7.,   0.,   1., ...,   4.,  67.,  35.],
       [  7.,   0.,   1., ...,   4.,  67.,  59.],
       [  7.,   0.,   1., ...,   4.,  67.,  38.]])

In [18]:
y_train.tail()

2517201    0
2517202    0
2517203    0
2517204    1
2517205    1
Name: PURCHASE_FLG, dtype: int64

---

### 2. Modeling

 - 조건부 확률 모형 : 각 클래스가 정답일 조건부 확률을 계산

    - 조건부 확률기반 생성모형 : 베이즈 정리를 사용

        - LDA (linear discriminant analysis)
        - QDA (Quadratic Discriminanat Analysis)
        - 나이브 베이지안 (Naive Bayes)
    
    - 조건부 확률기반 판별모형 :  직접 조건부 확률 함수를 추정
    
        - 로지스틱 회귀 (Logistic Regression)
        - 의사결정나무 (Descision Tree)
        - KNN (K Nearest Neighbor)
        
        
- 판별함수 모형 : 경계면을 찾아서 데이터가 어느 위치에 있는지 계산

    - 퍼셉트론 (Perceptron)
    - 서포트 벡터 머신 (Support Vector Machine)
    - 신경망 (Neural Network)  
    
    
- 모형결합 (Ensemble) : 복수의 예측모형을 결합하여 더 나은 성능을 예측하려는 시도

    - 취합 방법론 : 사용할 모형의 집합이 이미 결정되어 있음
        
        - 다수결 (Majority voting)
        - 배깅 (Bagging)
        - 랜덤 포레스트 (Random Forest)
        
    - 부스팅 방법론 : 사용할 모형을 점진적으로 늘림
    
        - 에이다 부스트 (AdaBoost)
        - 그레디언트 부스트 (Gradient Boost)

---

#### 2.1 조건부 확률모형

##### 2.1.1 조건부 확률기반 생성 모형

In [19]:
# LDA (linear discriminant analysis) (score : 0.000685)
model = LinearDiscriminantAnalysis(n_components=3, solver="svd", 
        store_covariance=True).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('LDA.csv', header=True)

In [20]:
# QDA (Quadratic Discriminanat Analysis) (score : 0.000234)
model = QuadraticDiscriminantAnalysis().fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('QDA.csv', header=True)

In [21]:
# Naive bayesian - Multinomial (score : 0.000450)
model = MultinomialNB(alpha = 0.001).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('NBM.csv', header=True)

---

##### 2.1.2 조건부 확률기반 판별모형

In [22]:
# Logistic Regression (0.000973)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=500).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('Logistic.csv', header=True)

In [23]:
# Descision Tree (0.000602)
model = DecisionTreeClassifier(criterion='entropy', 
        max_depth=7, min_samples_leaf=5).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('DT.csv', header=True)

In [14]:
# KNN (K Nearest Neighbor)

---

#### 2.2 모형결합 (Ensemble)

##### 2.2.1 취합 방법론

In [32]:
# 다수결 (Majority voting)

# 취합할 모델 생성
model1 = LinearDiscriminantAnalysis(n_components=3, solver="svd", store_covariance=True)
model2 = QuadraticDiscriminantAnalysis()
model3 = GaussianNB()
model4 = MultinomialNB()

# ensemble 생성
ensemble = VotingClassifier(estimators=[('lda', model1), ('qda', model2), ('gnb', model3), ('mul', model4)], 
                            voting='soft', weights=[1, 1, 1, 1])

predict_proba = [c.fit(X_train, y_train).predict_proba(X_test) for c in (model1, model2, model3, model4, ensemble)]

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('ensemble.csv', index = False, header=True)

TypeError: list indices must be integers or slices, not tuple

In [24]:
# 배깅 (Bagging) (score : 0.001133)
model1 = DecisionTreeClassifier().fit(X_train, y_train)
model2 = BaggingClassifier(DecisionTreeClassifier(), bootstrap_features=True, random_state=0).fit(X_train, y_train)
predict_proba = model2.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('Bagging.csv', header=True)

In [25]:
# 랜덤포레스트 (RandomForest) (score : 0.000689)
clf = RandomForestClassifier(n_estimators=500, max_depth=5, min_samples_split = 10, criterion = 'entropy')
model = clf.fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('RandomForest.csv', header=True)

---

##### 2.2.2 부스팅 방법론

In [26]:
# 에이다 부스트 (Ada Boost)
model = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5, random_state=0), 
                               algorithm="SAMME", n_estimators=100).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('Ada.csv', header=True)

In [27]:
# 그레디언트 부스트 (Gradient Boost)
model = GradientBoostingClassifier(n_estimators=100, max_depth=2, random_state=0).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('Gradient.csv', header=True)

In [28]:
# XG boost
model = xgboost.XGBClassifier(n_estimators=200, max_depth=3).fit(X_train, y_train)
predict_proba = model.predict_proba(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('XG1.csv',  header=True)

---

#### 2.3 판별함수 모형

In [38]:
# 퍼셉트론 (Perceptron) - perceptron
model = Perceptron(max_iter=500, eta0=0.1, random_state=1).fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('Perceptron.csv', header=True)

IndexError: too many indices for array

In [ ]:
# 퍼셉트론 (Perceptron) - SGD
model = SGDClassifier(loss="hinge", max_iter=3, random_state=1).fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('SGD.csv', header=True)

In [23]:
# 서포트 벡터 머신 (Support Vector Machine) - linear
model = SVC(kernel='linear').fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('NBM.csv', header=True)

Confusion Matrix : 

 [[281   0   0]
 [281   0   0]
 [198   0   0]]


 Classification Report : 

              precision    recall  f1-score   support

       Lose       0.37      1.00      0.54       281
        Win       0.00      0.00      0.00       281
       Draw       0.00      0.00      0.00       198

avg / total       0.14      0.37      0.20       760



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
# 서포트 벡터 머신 (Support Vector Machine) - 다항 커널 (Polynomial Kernel)
model = SVC(kernel="poly", degree=2, gamma=1, coef0=0).fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('NBM.csv', header=True)

Confusion Matrix : 

 [[281   0   0]
 [281   0   0]
 [198   0   0]]


 Classification Report : 

              precision    recall  f1-score   support

       Lose       0.37      1.00      0.54       281
        Win       0.00      0.00      0.00       281
       Draw       0.00      0.00      0.00       198

avg / total       0.14      0.37      0.20       760



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [25]:
# 서포트 벡터 머신 (Support Vector Machine) - RBF(Radial Basis Function)
model = SVC(kernel="rbf").fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('NBM.csv', header=True)

Confusion Matrix : 

 [[281   0   0]
 [281   0   0]
 [198   0   0]]


 Classification Report : 

              precision    recall  f1-score   support

       Lose       0.37      1.00      0.54       281
        Win       0.00      0.00      0.00       281
       Draw       0.00      0.00      0.00       198

avg / total       0.14      0.37      0.20       760



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [26]:
# 서포트 벡터 머신 (Support Vector Machine) - 시그모이드 커널 (Sigmoid Kernel)
model = SVC(kernel="sigmoid", gamma=2, coef0=2).fit(X_train, y_train)
predict_proba = model.predict(X_test)

# Top 10 Coupon
pos_idx = np.where(model.classes_ == True)[0][0]
test['predict'] = predict_proba[:, pos_idx]
top10_coupon = test.groupby('USER_ID_hash').apply(top_merge)
top10_coupon.name = 'PURCHASED_COUPONS'
top10_coupon.to_csv('NBM.csv', header=True)

Confusion Matrix : 

 [[281   0   0]
 [281   0   0]
 [198   0   0]]


 Classification Report : 

              precision    recall  f1-score   support

       Lose       0.37      1.00      0.54       281
        Win       0.00      0.00      0.00       281
       Draw       0.00      0.00      0.00       198

avg / total       0.14      0.37      0.20       760



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
# 신경망 (Neural Network)